import { join } from "node:path";
import { PHASE_OWNER, ROLES, WORKFLOW_PHASES } from "./defaults.mjs";
import { hashObject, newId, nowIso, readJson, readJsonl, writeJson, writeText } from "./fs-utils.mjs";
import { retrieveGlobalExperience } from "./memory.mjs";
import { scanProjectContext } from "./context.mjs";
import { appendDecisionEvent, appendTraceEvent, createGoal, initProject, readProjectState, writeProjectState } from "./project.mjs";
import { projectPaths } from "./paths.mjs";
import { exportAuditBundle, recordArtifact, recordBacklog } from "./trace.mjs";

export async function advanceWorkflow(projectRoot, input = {}) {
  await initProject(projectRoot);
  const maxSteps = Number(input.max_steps || input.maxSteps || 20);
  const adapter = input.adapter || "codex";
  const actions = [];

  for (let step = 0; step < maxSteps; step += 1) {
    let state = await readProjectState(projectRoot);
    let goal = activeGoal(state);

    if (!goal) {
      if (!input.title && !input.description && !input.goal) {
        const result = {
          status: "needs_goal",
          reason: "No active goal exists. Provide title/description or call create_goal.",
          actions
        };
        await recordAdvanceEvent(projectRoot, result);
        return result;
      }
      const created = await createGoal(projectRoot, {
        title: input.title || input.goal || "Untitled goal",
        description: input.description || input.goal || "",
        risk_level: input.risk_level || input.risk || "medium",
        created_by: input.created_by || "advance_workflow"
      });
      actions.push({ action: "create_goal", result: summarize(created) });
      continue;
    }

    if (state.current_phase === "intake") {
      const gate = await runGate(projectRoot, { phase: "intake" });
      actions.push({ action: "run_gate", phase: "intake", result: summarize(gate) });
      continue;
    }

    if (state.current_phase === "context_scan") {
      const context = await scanProjectContext(projectRoot);
      actions.push({ action: "scan_project_context", result: summarize(context) });
      const gate = await runGate(projectRoot, { phase: "context_scan" });
      actions.push({ action: "run_gate", phase: "context_scan", result: summarize(gate) });
      continue;
    }

    if (state.current_phase === "experience_retrieval") {
      const memory = await retrieveGlobalExperience(projectRoot, {
        query: `${goal.title} ${goal.description || ""}`,
        limit: input.memory_limit || input.memoryLimit || 8
      });
      actions.push({ action: "retrieve_global_experience", result: summarize(memory) });
      const gate = await runGate(projectRoot, { phase: "experience_retrieval" });
      actions.push({ action: "run_gate", phase: "experience_retrieval", result: summarize(gate) });
      continue;
    }

    if (state.current_phase === "clarification_gate") {
      const pending = (state.pending_decisions || []).filter((decision) => decision.status !== "answered");
      if (pending.length > 0) {
        const result = {
          status: "user_input_required",
          reason: "Workflow is waiting for a user decision.",
          pending_decisions: pending,
          actions
        };
        await recordAdvanceEvent(projectRoot, result);
        return result;
      }
      if (shouldAskForGoalClarification(goal, input)) {
        const decision = await askUserDecision(projectRoot, {
          topic: !goal.target_users ? "target_users" : "success_metrics",
          impact: "high"
        });
        actions.push({ action: "ask_user_decision", result: summarize(decision) });
        const result = {
          status: "user_input_required",
          reason: "A high-impact product decision cannot be inferred safely.",
          pending_decisions: [decision.decision],
          actions
        };
        await recordAdvanceEvent(projectRoot, result);
        return result;
      }
      const gate = await runGate(projectRoot, { phase: "clarification_gate" });
      actions.push({ action: "run_gate", phase: "clarification_gate", result: summarize(gate) });
      continue;
    }

    if (state.current_phase === "requirements") {
      const artifact = await recordArtifact(projectRoot, {
        artifact_type: "requirements",
        role: "pm",
        title: `Requirements for ${goal.title}`,
        content: renderAutoRequirements(goal, await readLatestContext(projectRoot), await readJsonl(projectPaths(projectRoot).decisionLog)),
        assumptions: ["Generated by advance_workflow from the active goal, project scan, and recorded decisions."]
      });
      actions.push({ action: "record_artifact", artifact_type: "requirements", result: summarize(artifact) });
      const gate = await runGate(projectRoot, { phase: "requirements" });
      actions.push({ action: "run_gate", phase: "requirements", result: summarize(gate) });
      continue;
    }

    if (state.current_phase === "architecture") {
      const artifact = await recordArtifact(projectRoot, {
        artifact_type: "adr",
        role: "architect",
        title: `ADR for ${goal.title}`,
        content: renderAutoAdr(goal, await readLatestContext(projectRoot)),
        assumptions: ["Architecture draft is generated automatically and must be refined by Architect role for high-risk implementation."]
      });
      actions.push({ action: "record_artifact", artifact_type: "adr", result: summarize(artifact) });
      const gate = await runGate(projectRoot, { phase: "architecture" });
      actions.push({ action: "run_gate", phase: "architecture", result: summarize(gate) });
      continue;
    }

    if (state.current_phase === "planning") {
      const backlog = await recordBacklog(projectRoot, {
        role: "delivery_manager",
        items: buildAutoBacklog(goal)
      });
      actions.push({ action: "record_backlog", result: summarize(backlog) });
      const gate = await runGate(projectRoot, { phase: "planning" });
      actions.push({ action: "run_gate", phase: "planning", result: summarize(gate) });
      continue;
    }

    if (state.current_phase === "build_loop") {
      const dispatch = await dispatchAgentTask(projectRoot, {
        adapter,
        role: "developer",
        objective: `Implement the next planned slice for: ${goal.title}`
      });
      actions.push({ action: "dispatch_agent_task", role: "developer", result: summarize(dispatch) });
      const result = {
        status: "external_agent_required",
        reason: "Developer implementation requires an execution agent. The workflow created and recorded the task packet.",
        dispatch,
        actions
      };
      await recordAdvanceEvent(projectRoot, result);
      return result;
    }

    if (state.current_phase === "verification_loop") {
      const dispatch = await dispatchAgentTask(projectRoot, {
        adapter,
        role: "qa",
        objective: `Verify implementation evidence for: ${goal.title}`
      });
      actions.push({ action: "dispatch_agent_task", role: "qa", result: summarize(dispatch) });
      const result = {
        status: "external_agent_required",
        reason: "Verification requires QA/Security/SRE execution and evidence recording.",
        dispatch,
        actions
      };
      await recordAdvanceEvent(projectRoot, result);
      return result;
    }

    if (state.current_phase === "review_gate") {
      const dispatch = await dispatchAgentTask(projectRoot, {
        adapter,
        role: "reviewer",
        objective: `Review changes and evidence for: ${goal.title}`
      });
      actions.push({ action: "dispatch_agent_task", role: "reviewer", result: summarize(dispatch) });
      const result = {
        status: "external_agent_required",
        reason: "Review gate requires independent review evidence.",
        dispatch,
        actions
      };
      await recordAdvanceEvent(projectRoot, result);
      return result;
    }

    if (state.current_phase === "release_readiness") {
      const artifact = await recordArtifact(projectRoot, {
        artifact_type: "release",
        role: "sre",
        title: `Release readiness for ${goal.title}`,
        content: renderAutoRelease(goal),
        assumptions: ["Release readiness was generated from recorded workflow state and still requires real deployment evidence if deployment is in scope."]
      });
      actions.push({ action: "record_artifact", artifact_type: "release", result: summarize(artifact) });
      const gate = await runGate(projectRoot, { phase: "release_readiness" });
      actions.push({ action: "run_gate", phase: "release_readiness", result: summarize(gate) });
      continue;
    }

    if (state.current_phase === "retro_learn") {
      const dispatch = await dispatchAgentTask(projectRoot, {
        adapter,
        role: "learning_coach",
        objective: `Create evidence-backed learning proposals for: ${goal.title}`
      });
      actions.push({ action: "dispatch_agent_task", role: "learning_coach", result: summarize(dispatch) });
      const result = {
        status: "external_agent_required",
        reason: "Learning proposals must be based on real evidence and should be produced by the Learning Coach role.",
        dispatch,
        actions
      };
      await recordAdvanceEvent(projectRoot, result);
      return result;
    }

    if (state.current_phase === "archive") {
      const audit = await exportAuditBundle(projectRoot, { task_id: state.active_task_id });
      actions.push({ action: "export_audit_bundle", result: summarize(audit) });
      const result = {
        status: "complete",
        reason: "Workflow reached archive and exported an audit bundle.",
        audit,
        actions
      };
      await recordAdvanceEvent(projectRoot, result);
      return result;
    }

    const result = {
      status: "blocked",
      reason: `Unknown phase: ${state.current_phase}`,
      actions
    };
    await recordAdvanceEvent(projectRoot, result);
    return result;
  }

  const result = {
    status: "step_limit_reached",
    reason: `Stopped after ${maxSteps} automatic steps.`,
    actions
  };
  await recordAdvanceEvent(projectRoot, result);
  return result;
}

export async function getRoleAction(projectRoot, input = {}) {
  await initProject(projectRoot);
  const state = await readProjectState(projectRoot);
  const role = normalizeRole(input.role || PHASE_OWNER[state.current_phase] || "delivery_manager");
  const roleDef = ROLES[role];
  if (!roleDef) return { ok: false, reason: `Unknown role: ${input.role}` };

  const context = await readLatestContext(projectRoot);
  const memoryQuery = [
    input.objective,
    state.current_phase,
    role,
    state.goals?.find((goal) => goal.task_id === state.active_task_id)?.title
  ].filter(Boolean).join(" ");
  const memory = await retrieveGlobalExperience(projectRoot, {
    query: memoryQuery,
    limit: input.limit || 8,
    scopes: inferScopes(context)
  });
  const packet = buildRolePacket({ state, role, roleDef, context, memory, objective: input.objective || "" });
  const promptRef = hashObject(packet);
  const paths = projectPaths(projectRoot);
  const packetFile = join(paths.taskPackets, `${packet.packet_id}.json`);
  const packetMd = join(paths.taskPackets, `${packet.packet_id}.md`);
  await writeJson(packetFile, { ...packet, prompt_ref: promptRef });
  await writeText(packetMd, renderRolePacketMarkdown({ ...packet, prompt_ref: promptRef }));

  await appendTraceEvent(projectRoot, {
    type: "role_action_created",
    task_id: state.active_task_id,
    role,
    phase: state.current_phase,
    prompt_ref: promptRef,
    context_ref: context?.hash || null,
    artifact_refs: [packetFile, packetMd]
  });

  return {
    ok: true,
    role,
    phase: state.current_phase,
    prompt_ref: promptRef,
    packet,
    files: {
      json: packetFile,
      markdown: packetMd
    }
  };
}

async function recordAdvanceEvent(projectRoot, result) {
  await appendTraceEvent(projectRoot, {
    type: "workflow_advanced",
    role: "delivery_manager",
    status: result.status,
    reason: result.reason,
    action_count: result.actions?.length || 0
  });
}

function shouldAskForGoalClarification(goal, input) {
  if (input.skip_questions || input.skipQuestions) return false;
  return !goal.target_users || !goal.success_metrics?.length;
}

function summarize(value) {
  if (!value || typeof value !== "object") return value;
  return {
    ok: value.ok,
    status: value.status,
    phase: value.phase,
    next_phase: value.next_phase,
    passed: value.passed,
    role: value.role,
    prompt_ref: value.prompt_ref,
    count: value.count,
    file: value.file,
    files: value.files,
    id: value.goal?.task_id || value.decision?.decision_id || value.dispatch?.dispatch_id || value.artifact?.artifact_id || value.bundle_id || value.learning?.id || null
  };
}

export async function askUserDecision(projectRoot, input = {}) {
  await initProject(projectRoot);
  const state = await readProjectState(projectRoot);
  const goal = activeGoal(state);
  const question = buildDecisionQuestion({ state, goal, input });
  state.pending_decisions.push(question);
  await writeProjectState(projectRoot, state);
  await appendDecisionEvent(projectRoot, {
    type: "decision_requested",
    task_id: state.active_task_id,
    decision_id: question.decision_id,
    question: question.question,
    default_assumption: question.default_assumption,
    affected_roles: question.affected_roles,
    affected_gates: question.affected_gates
  });
  await appendTraceEvent(projectRoot, {
    type: "decision_requested",
    task_id: state.active_task_id,
    role: "pm",
    decision_id: question.decision_id,
    summary: question.question
  });
  return {
    ok: true,
    decision: question
  };
}

export async function recordUserDecision(projectRoot, input = {}) {
  await initProject(projectRoot);
  const decisionId = input.decision_id || input.id;
  if (!decisionId) return { ok: false, reason: "decision_id is required" };
  const state = await readProjectState(projectRoot);
  const decision = state.pending_decisions.find((item) => item.decision_id === decisionId);
  if (!decision) return { ok: false, reason: `No pending decision found for ${decisionId}` };
  decision.status = "answered";
  decision.answer = input.answer || "";
  decision.answered_by = input.answered_by || input.by || "user";
  decision.answered_at = nowIso();
  await writeProjectState(projectRoot, state);
  await appendDecisionEvent(projectRoot, {
    type: "decision_answered",
    task_id: state.active_task_id,
    decision_id: decisionId,
    answer: decision.answer,
    answered_by: decision.answered_by,
    affected_roles: decision.affected_roles,
    affected_gates: decision.affected_gates
  });
  await appendTraceEvent(projectRoot, {
    type: "decision_answered",
    task_id: state.active_task_id,
    role: "pm",
    decision_id: decisionId,
    summary: decision.answer
  });
  return {
    ok: true,
    decision
  };
}

export async function dispatchAgentTask(projectRoot, input = {}) {
  await initProject(projectRoot);
  const adapter = input.adapter || "codex";
  const role = input.role || "developer";
  const roleAction = await getRoleAction(projectRoot, {
    role,
    objective: input.objective || ""
  });
  if (!roleAction.ok) return roleAction;
  const taskId = roleAction.packet.task_id;
  const dispatch = {
    dispatch_id: newId("dispatch"),
    adapter,
    role,
    task_id: taskId,
    prompt_ref: roleAction.prompt_ref,
    mode: "external_agent",
    owns_workflow_decisions: false,
    instructions: adapterInstructions(adapter, roleAction.files.markdown),
    created_at: nowIso()
  };
  await appendTraceEvent(projectRoot, {
    type: "agent_task_dispatched",
    task_id: taskId,
    role,
    agent: adapter,
    dispatch_id: dispatch.dispatch_id,
    prompt_ref: dispatch.prompt_ref,
    artifact_refs: [roleAction.files.markdown]
  });
  return {
    ok: true,
    dispatch,
    role_action: roleAction
  };
}

export async function runGate(projectRoot, input = {}) {
  await initProject(projectRoot);
  const state = await readProjectState(projectRoot);
  const phase = input.phase || state.current_phase;
  const paths = projectPaths(projectRoot);
  const trace = await readJsonl(paths.traceLedger);
  const decisions = await readJsonl(paths.decisionLog);
  const evidence = await loadEvidence(paths);
  const changesets = await loadChangesets(paths);
  const artifacts = await listArtifactNames(paths);
  const findings = gateFindings({ phase, state, trace, decisions, evidence, changesets, artifacts });
  const passed = findings.every((finding) => finding.severity !== "blocker");
  let next_phase = state.current_phase;

  if (passed && phase === state.current_phase) {
    const index = WORKFLOW_PHASES.indexOf(phase);
    if (index >= 0 && index < WORKFLOW_PHASES.length - 1) {
      next_phase = WORKFLOW_PHASES[index + 1];
      state.current_phase = next_phase;
      state.phase_history.push({ phase: next_phase, task_id: state.active_task_id, entered_at: nowIso() });
      const owner = PHASE_OWNER[next_phase];
      if (owner && !state.role_queue.includes(owner)) state.role_queue.push(owner);
      await writeProjectState(projectRoot, state);
    }
  }

  await appendTraceEvent(projectRoot, {
    type: "gate_run",
    task_id: state.active_task_id,
    role: PHASE_OWNER[phase] || "delivery_manager",
    phase,
    passed,
    next_phase,
    findings
  });

  return {
    ok: true,
    phase,
    passed,
    next_phase,
    findings
  };
}

function normalizeRole(role) {
  return String(role || "").toLowerCase().replace(/[\s-]+/g, "_");
}

async function readLatestContext(projectRoot) {
  const paths = projectPaths(projectRoot);
  return readJson(join(paths.context, "latest-context.json"), null);
}

function activeGoal(state) {
  return (state.goals || []).find((goal) => goal.task_id === state.active_task_id) || state.goals?.at(-1) || null;
}

function inferScopes(context) {
  if (!context) return ["global"];
  const scopes = ["global"];
  for (const language of Object.keys(context.language_counts || {})) {
    scopes.push(`stack:${language}`);
  }
  return scopes;
}

function buildRolePacket({ state, role, roleDef, context, memory, objective }) {
  const goal = activeGoal(state);
  return {
    packet_id: newId("packet"),
    task_id: state.active_task_id,
    phase: state.current_phase,
    role,
    role_title: roleDef.title,
    mission: roleDef.mission,
    objective: objective || goal?.title || state.current_phase,
    goal,
    required_inputs: roleDef.inputs,
    required_outputs: roleDef.outputs,
    gates: roleDef.gates,
    project_context_ref: context?.hash || null,
    project_context_summary: context ? {
      file_count: context.file_count,
      language_counts: context.language_counts,
      notable_files: context.notable_files,
      ci_files: context.ci_files,
      inferred_test_commands: context.inferred_test_commands
    } : null,
    global_experience: memory.experiences || [],
    operating_rules: [
      "Explore repository facts before asking the user.",
      "Ask the user only for decisions that materially affect product behavior, cost, compliance, architecture, or risk.",
      "Record assumptions in the decision log.",
      "Every code modification must produce a ChangeSet with diff hash, commands, tests, evidence, review references, and rollback plan.",
      "Do not bypass tests, security checks, review gates, or trace requirements."
    ],
    expected_next_action: expectedNextAction(role, state.current_phase),
    created_at: nowIso()
  };
}

function expectedNextAction(role, phase) {
  if (phase === "context_scan") return "Run or request scan_project_context, then retrieve global experience.";
  if (phase === "clarification_gate") return "Generate only high-impact user questions that cannot be answered from context.";
  if (role === "developer") return "Implement the smallest useful slice, run relevant checks, then record a ChangeSet.";
  if (role === "reviewer") return "Review ChangeSets against requirements, ADR, evidence, and rollback plan.";
  if (role === "trace_auditor") return "Export an audit bundle and report missing traceability.";
  return "Produce the role outputs and record artifacts or evidence before running the next gate.";
}

function renderRolePacketMarkdown(packet) {
  return [
    `# ${packet.role_title} Task Packet`,
    "",
    `- Packet ID: ${packet.packet_id}`,
    `- Task ID: ${packet.task_id || "none"}`,
    `- Phase: ${packet.phase}`,
    `- Prompt ref: ${packet.prompt_ref}`,
    "",
    "## Mission",
    "",
    packet.mission,
    "",
    "## Objective",
    "",
    packet.objective || "_No objective provided._",
    "",
    "## Required Outputs",
    "",
    ...packet.required_outputs.map((item) => `- ${item}`),
    "",
    "## Operating Rules",
    "",
    ...packet.operating_rules.map((item) => `- ${item}`),
    "",
    "## Global Experience",
    "",
    ...(packet.global_experience.length
      ? packet.global_experience.map((item) => `- ${item.id}: ${item.lesson}`)
      : ["- No matching global experience found."]),
    "",
    "## Project Context",
    "",
    packet.project_context_summary ? JSON.stringify(packet.project_context_summary, null, 2) : "_No scan found. Run scan_project_context._",
    "",
    "## Expected Next Action",
    "",
    packet.expected_next_action,
    ""
  ].join("\n");
}

function buildDecisionQuestion({ state, goal, input }) {
  const topic = input.topic || inferQuestionTopic(goal);
  const impact = input.impact || "high";
  const decisionId = input.decision_id || newId("decision");
  const base = {
    decision_id: decisionId,
    task_id: state.active_task_id,
    topic,
    impact,
    status: "pending",
    created_at: nowIso()
  };
  if (topic === "target_users") {
    return {
      ...base,
      question: "Who are the primary users for this product or feature?",
      recommended_option: "Use the most likely target users from the product goal, then validate during review.",
      alternatives: ["Ask for a named persona", "Treat it as an internal engineering tool until corrected"],
      default_assumption: "Primary users are developers using AI coding agents.",
      affected_roles: ["pm", "qa", "writer"],
      affected_gates: ["requirements", "review_gate"]
    };
  }
  if (topic === "success_metrics") {
    return {
      ...base,
      question: "What measurable result defines success for this product or feature?",
      recommended_option: "Use observable delivery and quality metrics tied to the stated goal.",
      alternatives: ["Use user acceptance only", "Use operational metrics only"],
      default_assumption: "Success means the AI can produce a traceable deliverable with passing verification and audit export.",
      affected_roles: ["pm", "delivery_manager", "qa", "trace_auditor"],
      affected_gates: ["requirements", "release_readiness", "archive"]
    };
  }
  return {
    ...base,
    question: input.question || `Please clarify: ${topic}`,
    recommended_option: input.recommended_option || "Proceed with the safest reversible option.",
    alternatives: input.alternatives || ["Pause until clarified", "Use a narrow assumption and record it"],
    default_assumption: input.default_assumption || "Use a conservative, reversible default and record it in the decision log.",
    affected_roles: input.affected_roles || ["pm", "architect", "delivery_manager"],
    affected_gates: input.affected_gates || ["clarification_gate", "requirements"]
  };
}

function inferQuestionTopic(goal) {
  if (!goal?.target_users) return "target_users";
  if (!goal?.success_metrics?.length) return "success_metrics";
  return "decision";
}

function renderAutoRequirements(goal, context, decisions) {
  const answered = decisions
    .filter((decision) => decision.type === "decision_answered")
    .map((decision) => `- ${decision.decision_id}: ${decision.answer}`)
    .join("\n") || "- None recorded yet.";
  return [
    "## Product Goal",
    "",
    goal.description || goal.title,
    "",
    "## Target Users",
    "",
    goal.target_users || "Assumption: AI coding agents and the operators who supervise engineering delivery.",
    "",
    "## Success Criteria",
    "",
    goal.success_metrics?.length
      ? goal.success_metrics.map((metric) => `- ${metric}`).join("\n")
      : "- A role task packet is generated for the next responsible role.\n- Required artifacts, evidence, and ChangeSets are recorded.\n- Gates block missing evidence.\n- An audit bundle can trace requirement to implementation evidence.",
    "",
    "## Scope",
    "",
    "- Use the current repository context as the source of implementation truth.",
    "- Keep changes small, reversible, and traceable.",
    "- Ask the user only for high-impact product, architecture, compliance, cost, deletion, migration, or public API decisions.",
    "",
    "## Project Context Summary",
    "",
    context ? `- Files scanned: ${context.file_count}\n- Languages: ${Object.keys(context.language_counts || {}).join(", ") || "unknown"}\n- Test commands: ${(context.inferred_test_commands || []).join(", ") || "none inferred"}` : "- No project context scan found.",
    "",
    "## Recorded User Decisions",
    "",
    answered,
    ""
  ].join("\n");
}

function renderAutoAdr(goal, context) {
  return [
    "## Status",
    "",
    "Draft generated by workflow automation.",
    "",
    "## Context",
    "",
    `The active goal is: ${goal.title}.`,
    context ? `The repository scan found ${context.file_count} files and inferred test commands: ${(context.inferred_test_commands || []).join(", ") || "none"}.` : "No repository scan is available.",
    "",
    "## Decision",
    "",
    "- Use the virtual engineering team workflow as the delivery control plane.",
    "- Use role task packets for execution agents instead of free-form tool sequencing.",
    "- Require ChangeSet, Evidence, and Audit Bundle records for traceability.",
    "",
    "## Consequences",
    "",
    "- Implementation agents can be replaced without changing workflow state.",
    "- Missing evidence blocks gates instead of relying on agent claims.",
    "- High-risk details should be refined by the Architect role before code changes.",
    "",
    "## Rollback",
    "",
    "Revert the ChangeSet patch snapshots or restore affected files from version control.",
    ""
  ].join("\n");
}

function buildAutoBacklog(goal) {
  return [
    {
      title: `Implement smallest traceable slice for ${goal.title}`,
      description: "Developer executes the next reversible implementation step and records a ChangeSet.",
      role: "developer",
      priority: 1,
      definition_of_done: [
        "Implementation is scoped to the active goal",
        "Relevant tests or checks have evidence records",
        "ChangeSet includes prompt_ref, context_ref, files_changed, evidence_refs, and rollback_plan"
      ],
      risk_level: goal.risk_level || "medium"
    },
    {
      title: `Verify ${goal.title}`,
      description: "QA/Security/SRE verify behavior, security, and operational readiness as relevant.",
      role: "qa",
      priority: 2,
      definition_of_done: [
        "Test, scan, or manual verification evidence is recorded",
        "Failures are linked to follow-up ChangeSets or blocking findings"
      ],
      risk_level: goal.risk_level || "medium"
    },
    {
      title: `Review and audit ${goal.title}`,
      description: "Reviewer and Trace Auditor validate maintainability, evidence, and traceability.",
      role: "reviewer",
      priority: 3,
      definition_of_done: [
        "Review evidence is approved or blocking issues are recorded",
        "Audit bundle has no missing trace findings for complete ChangeSets"
      ],
      risk_level: goal.risk_level || "medium"
    }
  ];
}

function renderAutoRelease(goal) {
  return [
    "## Release Summary",
    "",
    `Goal: ${goal.title}`,
    "",
    "## Readiness Checklist",
    "",
    "- Requirements artifact recorded.",
    "- Architecture artifact recorded.",
    "- Backlog recorded.",
    "- ChangeSets are traceable.",
    "- Verification evidence is recorded.",
    "- Review evidence is recorded before delivery.",
    "",
    "## Rollback",
    "",
    "Use recorded ChangeSet rollback plans and patch snapshots.",
    "",
    "## Notes",
    "",
    "This release readiness artifact is generated automatically. Real deployment remains out of scope unless deployment evidence is recorded.",
    ""
  ].join("\n");
}

function adapterInstructions(adapter, packetPath) {
  const base = `Use the task packet at ${packetPath}. Follow the role, produce required artifacts, then record evidence and a ChangeSet.`;
  if (adapter === "codex") {
    return `${base} In Codex, open the repository, read the packet, execute the work, and call record_changeset after edits.`;
  }
  if (adapter === "claude_code") {
    return `${base} In Claude Code, load the packet into the session, execute only the delegated role, and return evidence refs.`;
  }
  if (adapter === "cursor") {
    return `${base} In Cursor, paste the packet into the agent chat and keep changes scoped to the delegated task.`;
  }
  return base;
}

async function loadEvidence(paths) {
  const events = [];
  try {
    const files = await (await import("./fs-utils.mjs")).listFiles(paths.evidence, { maxDepth: 1, maxFiles: 5000, ignore: [] });
    for (const file of files.filter((item) => item.endsWith(".json"))) events.push(await readJson(file));
  } catch {
    return [];
  }
  return events;
}

async function loadChangesets(paths) {
  const changesets = [];
  try {
    const files = await (await import("./fs-utils.mjs")).listFiles(paths.changesets, { maxDepth: 1, maxFiles: 5000, ignore: [] });
    for (const file of files.filter((item) => item.endsWith(".json"))) changesets.push(await readJson(file));
  } catch {
    return [];
  }
  return changesets;
}

async function listArtifactNames(paths) {
  try {
    const { listFiles } = await import("./fs-utils.mjs");
    return await listFiles(paths.docsRoot, { maxDepth: 4, maxFiles: 5000, ignore: [] });
  } catch {
    return [];
  }
}

function gateFindings({ phase, state, trace, decisions, evidence, changesets, artifacts }) {
  const findings = [];
  const unresolved = (state.pending_decisions || []).filter((decision) => decision.status !== "answered");
  if (phase === "intake" && !state.active_task_id) {
    findings.push(blocker("No active task exists. Run create_goal first."));
  }
  if (phase === "context_scan" && !trace.some((event) => event.type === "context_scanned")) {
    findings.push(blocker("Project context has not been scanned."));
  }
  if (phase === "experience_retrieval" && !trace.some((event) => event.type === "experience_retrieved")) {
    findings.push(blocker("Global engineering experience has not been retrieved."));
  }
  if (phase === "clarification_gate" && unresolved.length > 0) {
    findings.push(blocker(`There are ${unresolved.length} unresolved user decisions.`));
  }
  if (phase === "requirements" && !artifacts.some((file) => file.includes("/requirements/"))) {
    findings.push(blocker("Requirements artifact is missing."));
  }
  if (phase === "architecture" && !artifacts.some((file) => file.includes("/adr/"))) {
    findings.push(blocker("Architecture ADR artifact is missing."));
  }
  if (phase === "planning" && (!state.backlog || state.backlog.length === 0)) {
    findings.push(blocker("Backlog is empty. Delivery Manager must split work into traceable tasks."));
  }
  if (phase === "build_loop" && changesets.length === 0) {
    findings.push(blocker("No ChangeSet has been recorded."));
  }
  if (phase === "verification_loop" && !evidence.some((item) => ["test", "scan", "security", "qa"].includes(item.evidence_type))) {
    findings.push(blocker("Verification evidence is missing."));
  }
  if (phase === "review_gate" && !evidence.some((item) => item.evidence_type === "review" && ["passed", "approved"].includes(item.outcome))) {
    findings.push(blocker("Passing review evidence is missing."));
  }
  if (phase === "release_readiness" && !artifacts.some((file) => file.includes("/release/"))) {
    findings.push(blocker("Release readiness artifact is missing."));
  }
  if (phase === "retro_learn" && !trace.some((event) => event.type === "learning_proposed")) {
    findings.push(warning("No learning proposal has been recorded yet."));
  }
  if (phase === "archive" && !trace.some((event) => event.type === "audit_bundle_exported")) {
    findings.push(blocker("Audit bundle has not been exported."));
  }
  if (findings.length === 0) findings.push({ severity: "info", message: "Gate passed." });
  return findings;
}

function blocker(message) {
  return { severity: "blocker", message };
}

function warning(message) {
  return { severity: "warning", message };
}
